[package]
name = "clod"
version = "0.1.0"
edition = "2024"

[dependencies]
binrw = "0.14"
xmltree = "0.11"
cursive = "0.21"
clap = { version = "4.5.47", features = ["derive"] }
refpack = "5.0.2"
regex = "1.11"
crc-any = "2.5"
